[package]
name = "review-domain"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
serde = { version = "1", optional = true, features = ["derive"] }
