[package]
name = "chess-training"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
	"crates/*",
]

[dev-dependencies]
assert_cmd = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0"
