[package]
name = "chess-training"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
        "crates/*",
]

[dev-dependencies]
assert_cmd = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
