name: Run with CI error logging
description: Run a command and capture logs when it exits with a non-zero status.
inputs:
  command:
    description: Command to execute.
    required: true
  label:
    description: Identifier used to name the log file.
    required: false
  working-directory:
    description: Directory in which to run the command.
    required: false
runs:
  using: composite
  steps:
    - id: run
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/run.sh" \
          --command "${{ inputs.command }}" \
          --label "${{ inputs.label }}" \
          --working-directory "${{ inputs.working-directory }}"
